# Generated by Django 2.2 on 2022-03-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='视频地址'),
        ),
    ]
