# Generated by Django 2.2 on 2022-03-03 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20220128_1508'),
        ('courses', '0005_video_learn_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='theacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='讲师'),
        ),
    ]
